hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

service:
  internalPort: 50051

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"

prometheus:
  metrics: false

livenessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 15
  probeType: "tcpSocket"

readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 3
  probeType: "tcpSocket"

podDisruptionBudget:
  enabled: true
  # minAvailable: 1
  maxUnavailable: 1

postgresql:
  enabled: false
